code --install-extension alefragnani.Bookmarks
code --install-extension ChakrounAnas.turbo-console-log
code --install-extension christian-kohler.npm-intellisense
code --install-extension christian-kohler.path-intellisense
code --install-extension dbaeumer.vscode-eslint
code --install-extension dracula-theme.theme-dracula
code --install-extension eamodio.gitlens
code --install-extension eg2.vscode-npm-script
code --install-extension Equinusocio.vsc-material-theme
code --install-extension ericadamski.carbon-now-sh
code --install-extension esbenp.prettier-vscode
code --install-extension firefox-devtools.vscode-firefox-debug
code --install-extension GitHub.vscode-pull-request-github
code --install-extension hoovercj.vscode-power-mode
code --install-extension jpoissonnier.vscode-styled-components
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-python.python
code --install-extension ms-vscode.vscode-typescript-tslint-plugin
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension msjsdiag.vscode-react-native
code --install-extension naumovs.color-highlight
code --install-extension pflannery.vscode-versionlens
code --install-extension rebornix.ruby
code --install-extension robinbentley.sass-indented
code --install-extension sdras.night-owl
code --install-extension shardulm94.trailing-spaces
code --install-extension sianglim.slim
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vscodevim.vim
code --install-extension WallabyJs.quokka-vscode
code --install-extension walter-ribeiro.full-react-snippets
code --install-extension wmaurer.change-case
code --install-extension yzhang.markdown-all-in-one
code --install-extension ziyasal.vscode-open-in-github
