code --install-extension alefragnani.Bookmarks
code --install-extension christian-kohler.npm-intellisense
code --install-extension christian-kohler.path-intellisense
code --install-extension dbaeumer.vscode-eslint
code --install-extension eamodio.gitlens
code --install-extension eg2.tslint
code --install-extension eg2.vscode-npm-script
code --install-extension esbenp.prettier-vscode
code --install-extension GitHub.vscode-pull-request-github
code --install-extension ms-python.python
code --install-extension PeterJausovec.vscode-docker
code --install-extension rebornix.ruby
code --install-extension robinbentley.sass-indented
code --install-extension shardulm94.trailing-spaces
code --install-extension sianglim.slim
code --install-extension walter-ribeiro.full-react-snippets
code --install-extension wmaurer.change-case
code --install-extension yzhang.markdown-all-in-one
code --install-extension ziyasal.vscode-open-in-github
